<?php

namespace AppBundle\Repository;

/**
 * gruposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gruposRepository extends \Doctrine\ORM\EntityRepository
{
}
